-- Auto-generated seed data

INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_sgcc', '国家电网有限公司 (State Grid)', '央国企', 'https://zhaopin.sgcc.com.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_csg', '中国南方电网有限责任公司 (China Southern Power Grid)', '央国企', 'https://zhaopin.csg.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_chinamobile', '中国移动通信集团有限公司 (China Mobile)', '央国企', 'https://job.10086.cn', 'https://job.10086.cn/api/v1/campus/jobs', 'dayee_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_chinatelecom', '中国电信集团有限公司 (China Telecom)', '央国企', 'https://job.chinatelecom.cn', '', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_chinaunicom', '中国联合网络通信集团有限公司 (China Unicom)', '央国企', 'https://zglt.zhaopin.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_cnpc', '中国石油天然气集团有限公司 (CNPC)', '央国企', 'https://zhaopin.cnpc.com.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_sinopec', '中国石油化工集团有限公司 (Sinopec)', '央国企', 'https://job.sinopec.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_crrc', '中国中车股份有限公司 (CRRC)', '央国企', 'https://crrcgc.zhaopin.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_avic', '中国航空工业集团有限公司 (AVIC)', '央国企', 'https://avic.zhiye.com', 'https://avic.zhiye.com/api/campus/positions', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_cscec', '中国建筑集团有限公司 (CSCEC)', '央国企', 'https://job.cscec.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_crcc', '中国铁建股份有限公司 (CRCC)', '央国企', 'https://crcc.zhiye.com', 'https://crcc.zhiye.com/api/positions', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_casc', '中国航天科技集团有限公司 (CASC)', '央国企', 'https://spacetalent.casc.com.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_chng', '中国华能集团有限公司 (China Huaneng)', '央国企', 'https://zhaopin.chng.com.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_sinochem', '中国中化控股有限责任公司 (Sinochem Holdings)', '央国企', 'https://sinochem.zhiye.com', 'https://sinochem.zhiye.com/api/positions', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_icbc', '中国工商银行 (ICBC)', '金融券商', 'https://job.icbc.com.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_ccb', '中国建设银行 (CCB)', '金融券商', 'http://job.ccb.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_boc', '中国银行 (Bank of China)', '金融券商', 'https://campus.chinahr.com/pages/boc', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_cmb', '招商银行股份有限公司 (China Merchants Bank)', '金融券商', 'https://career.cloud.cmbchina.com', 'https://career.cloud.cmbchina.com/api/campus/jobs', 'dayee_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_citics', '中信证券股份有限公司 (CITIC Securities)', '金融券商', 'https://customer.citics.com/recruitment', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_cicc', '中国国际金融股份有限公司 (CICC 中金公司)', '金融券商', 'https://cicc.zhiye.com', 'https://cicc.zhiye.com/api/positions', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_tencent', '腾讯控股有限公司 (Tencent)', '互联网大厂', 'https://join.qq.com', 'https://join.qq.com/api/v1/campus/positions', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_alibaba', '阿里巴巴集团 (Alibaba Group)', '互联网大厂', 'https://talent.alibaba.com/campus', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_bytedance', '字节跳动 (ByteDance)', '互联网大厂', 'https://job.bytedance.com/campus', 'https://job.bytedance.com/api/v1/search/job/posts', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_meituan', '美团 (Meituan)', '互联网大厂', 'https://zhaopin.meituan.com/web/campus', 'https://zhaopin.meituan.com/api/v1/campus/jobs', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_kuaishou', '快手科技 (Kuaishou)', '互联网大厂', 'https://campus.kuaishou.cn', 'https://campus.kuaishou.cn/api/v1/open/jobs', 'moka_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_baidu', '百度在线网络技术有限公司 (Baidu)', '互联网大厂', 'https://talent.baidu.com/jobs/campus-list', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_pdd', '拼多多 (Pinduoduo)', '互联网大厂', 'https://careers.pinduoduo.com/campus', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_antgroup', '蚂蚁科技集团股份有限公司 (Ant Group)', '互联网大厂', 'https://talent.antgroup.com/campus', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_xiaohongshu', '小红书 (RED)', '互联网大厂', 'https://job.xiaohongshu.com/campus', 'https://job.xiaohongshu.com/api/v1/campus/position/list', 'moka_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_netease', '网易公司 (NetEase / 互娱 & 雷火)', '互联网大厂', 'https://campus.163.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_huawei', '华为技术有限公司 (Huawei)', '智能制造', 'https://career.huawei.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_xiaomi', '小米集团 (Xiaomi)', '智能制造', 'https://hr.xiaomi.com/campus', 'https://hr.xiaomi.com/api/campus/jobs', 'dayee_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_byd', '比亚迪股份有限公司 (BYD)', '智能制造', 'https://job.byd.com', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_dji', '大疆创新科技有限公司 (DJI)', '智能制造', 'https://we.dji.com/zh-CN/campus', 'https://we.dji.com/api/v1/campus/positions', 'moka_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_catl', '宁德时代新能源科技股份有限公司 (CATL)', '智能制造', 'https://talent.catl.com', 'https://talent.catl.com/api/campus/positions', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_smic', '中芯国际集成电路制造有限公司 (SMIC)', '中国500强', 'https://smics.zhiye.com', 'https://smics.zhiye.com/api/positions', 'beisen_api', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_lenovo', '联想集团 (Lenovo)', '中国500强', 'https://talent.lenovo.com.cn', '', 'html_selector', 'active');
INSERT OR REPLACE INTO crawler_sources (id, company_name, category, portal_url, api_endpoint, parser_type, status) VALUES ('cs_haier', '海尔智家股份有限公司 (Haier)', '中国500强', 'https://maker.haier.net/campus', '', 'html_selector', 'active');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_001', '腾讯控股有限公司', '互联网/软件', '2027提前批', '["技术研发"]', '["深圳","北京","上海"]', '后台开发工程师（CSIG/TEG/IEG等核心事业群）', 'TXNEITUI2027', 'https://join.qq.com/post_detail.html?pid=1001', '2026-09-19T07:00:00.000Z', '2026-11-15T23:59:59Z', 'active', '行业领先薪资、全员免费班车及早晚免费三餐、房补安居计划50万', 1, '腾讯控股有限公司_后台开发工程师（CSIG/TEG/IEG等核心事业群）_https://join.qq.com/post_detail.html?pid=1001');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_002', '字节跳动', '互联网/人工智能', '2027提前批', '["技术研发"]', '["北京","上海","深圳","杭州"]', '大模型算法工程师（Seed基础模型团队）', 'BYTEDANCE99', 'https://job.bytedance.com/campus/position/detail/201', '2026-09-19T06:00:00.000Z', '2026-10-31T23:59:59Z', 'active', '顶尖GPU算力资源、无笔试直通面试、顶薪SP/SSP不设限、就近租房补贴', 1, '字节跳动_大模型算法工程师（Seed基础模型团队）_https://job.bytedance.com/campus/position/detail/201');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_003', '阿里巴巴集团', '互联网/电商', '2027提前批', '["技术研发"]', '["杭州","北京"]', 'Java研发工程师（淘天技术团队/通义千问）', 'ALI2027VIP', 'https://talent.alibaba.com/campus/position-detail?id=301', '2026-09-19T05:00:00.000Z', '2026-11-20T23:59:59Z', 'active', '双导师带教体系、核心高并发万亿级业务场景、无息置业贷款', 1, '阿里巴巴集团_Java研发工程师（淘天技术团队/通义千问）_https://talent.alibaba.com/campus/position-detail?id=301');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_004', '国家电网有限公司', '电力/能源', '2027秋招', '["技术研发","职能管培"]', '["北京","上海","南京","成都","全国"]', '电力系统及自动化/信息通信科研管培生', '', 'https://zhaopin.sgcc.com.cn/unitList.html', '2026-09-19T04:00:00.000Z', '2026-11-10T18:00:00Z', 'active', '中央直管央企六险二金、落户重点指标、稳定健全晋升通道', 1, '国家电网有限公司_电力系统及自动化/信息通信科研管培生_https://zhaopin.sgcc.com.cn/unitList.html');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_005', '华为技术有限公司', '通信/硬件/ICT', '2027秋招', '["技术研发"]', '["深圳","上海","北京","南京","西安","成都"]', '通用软件开发工程师（云计算/数通/无线产品线）', 'HWHR8899', 'https://career.huawei.com/reccam/campus/portal.html', '2026-09-19T03:00:00.000Z', '2026-12-31T23:59:59Z', 'active', '全员导师1对1辅导、全球化研发平台、丰厚年终绩效奖金与股票期权', 1, '华为技术有限公司_通用软件开发工程师（云计算/数通/无线产品线）_https://career.huawei.com/reccam/campus/portal.html');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_006', '中国工商银行', '银行/金融', '2027秋招', '["技术研发","金融业务"]', '["北京","上海","广州","全国"]', '科技菁英计划（总行软件开发中心/数据中心）', '', 'https://job.icbc.com.cn/pc/index.html', '2026-09-19T02:00:00.000Z', '2026-10-25T24:00:00Z', 'active', '六险二金、一线城市户口指标重点保障、总行平台战略级数字化转型孵化', 1, '中国工商银行_科技菁英计划（总行软件开发中心/数据中心）_https://job.icbc.com.cn/pc/index.html');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_007', '比亚迪股份有限公司', '新能源汽车/高端制造', '2027秋招', '["技术研发"]', '["深圳","西安","长沙","常州"]', '整车电子电气/智能底盘软件研发工程师', 'BYDSTAR2027', 'https://job.byd.com/portal/#/position/detail?id=701', '2026-09-19T01:00:00.000Z', '2026-12-15T23:59:59Z', 'active', '世界新能源汽车销冠平台、购车员工极高内购折扣、免费提供员工公寓', 1, '比亚迪股份有限公司_整车电子电气/智能底盘软件研发工程师_https://job.byd.com/portal/#/position/detail?id=701');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_008', '大疆创新科技有限公司', '智能硬件/机器人', '2027提前批', '["技术研发"]', '["深圳","上海"]', '嵌入式软硬件开发工程师（无人机/手持影像团队）', 'DJINEITUI666', 'https://we.dji.com/zh-CN/position/detail?id=801', '2026-09-18T23:00:00.000Z', '2026-11-01T23:59:59Z', 'active', '全球无人机领军企业、极客工程研发文化、零食饮料无限量、免费健身房及班车', 1, '大疆创新科技有限公司_嵌入式软硬件开发工程师（无人机/手持影像团队）_https://we.dji.com/zh-CN/position/detail?id=801');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_009', '中国移动通信集团有限公司', '电信运营商/云计算', '2027秋招', '["技术研发","市场运营"]', '["北京","广州","苏州","杭州","全国"]', '移研之星管培生（移动云/研究院/信息技术中心）', 'CMCC2027STAR', 'https://job.10086.cn/unit_list.html', '2026-09-18T21:00:00.000Z', '2026-10-30T23:59:59Z', 'active', '世界500强央企福利待遇、七险二金、定期体检与工会多维度暖心补贴', 1, '中国移动通信集团有限公司_移研之星管培生（移动云/研究院/信息技术中心）_https://job.10086.cn/unit_list.html');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_010', '美团', '互联网/本地生活', '2027秋招', '["产品经理"]', '["北京","上海","深圳","成都"]', '核心本地商业-产品经理（餐饮外卖/到店业务）', 'MT2027VIP', 'https://zhaopin.meituan.com/web/campus/position/detail?id=101', '2026-09-18T19:00:00.000Z', '2026-11-15T23:59:59Z', 'active', '产品圣经培训孵化营、亿级DAU真实消费互联网试炼场、弹性工时', 1, '美团_核心本地商业-产品经理（餐饮外卖/到店业务）_https://zhaopin.meituan.com/web/campus/position/detail?id=101');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_011', '快手科技', '互联网/短视频', '2027提前批', '["技术研发"]', '["北京","杭州","深圳"]', '推荐算法工程师（快星卓越人才项目）', 'KSSTAR2027', 'https://campus.kuaishou.cn/position/detail?id=1101', '2026-09-18T17:00:00.000Z', '2026-10-20T23:59:59Z', 'active', '顶配技术大牛直接带导、千万级日活流量反馈、高额签字费及期权激励', 1, '快手科技_推荐算法工程师（快星卓越人才项目）_https://campus.kuaishou.cn/position/detail?id=1101');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_012', '中国建筑集团有限公司', '建筑工程/基础设施', '2027秋招', '["职能管培","工程技术"]', '["北京","上海","武汉","广州","全国"]', '中建青苗工程管培生（一局/三局/八局核心局院）', '', 'https://job.cscec.com/job/detail?id=1201', '2026-09-18T15:00:00.000Z', '2026-11-30T23:59:59Z', 'active', '央企第一梯队龙头、国家级超级工程参建履历、落户政策与优厚工程津贴', 1, '中国建筑集团有限公司_中建青苗工程管培生（一局/三局/八局核心局院）_https://job.cscec.com/job/detail?id=1201');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_013', '小红书', '互联网/社交电商', '2027秋招', '["市场运营"]', '["上海","北京"]', '社区生态/商业化运营专家管培生', 'REDSTAR2027', 'https://job.xiaohongshu.com/campus/position/1301', '2026-09-18T13:00:00.000Z', '2026-11-10T23:59:59Z', 'active', '扁平开放的年轻化文化、上海新天地黄金办公圈、一日免费三餐+宠物友好', 1, '小红书_社区生态/商业化运营专家管培生_https://job.xiaohongshu.com/campus/position/1301');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_014', '中金公司 (CICC)', '投资银行/证券', '2027秋招', '["金融业务"]', '["北京","上海","深圳","香港"]', '投资银行部 (IBD) 分析师', 'CICCGRAD2027', 'https://cicc.zhiye.com/jobdetails/1401', '2026-09-18T11:00:00.000Z', '2026-10-18T23:59:59Z', 'active', '国内顶尖投行平台、明星IPO项目实操积累、与全球金融精英同行、高额Base+Bonus', 1, '中金公司 (CICC)_投资银行部 (IBD) 分析师_https://cicc.zhiye.com/jobdetails/1401');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_015', '腾讯控股有限公司', '互联网/软件', '2027提前批', '["产品经理"]', '["深圳","广州"]', '微信产品经理（开放平台/视频号/微信支付）', 'TXWXPRODUCT', 'https://join.qq.com/post_detail.html?pid=1015', '2026-09-17T10:00:00Z', '2026-11-20T23:59:59Z', 'active', '国民级产品决策参与、顶尖导师指导、腾讯学堂顶尖产品培训', 1, '腾讯控股有限公司_微信产品经理（开放平台/视频号/微信支付）_https://join.qq.com/post_detail.html?pid=1015');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_016', '字节跳动', '互联网/文娱', '2027秋招', '["产品经理"]', '["北京","上海","深圳"]', '抖音/TikTok核心产品经理', 'BYTEDANCE99', 'https://job.bytedance.com/campus/position/detail/216', '2026-09-17T11:30:00Z', '2026-11-30T23:59:59Z', 'active', '全球百国破圈产品影响力、数据驱动严密方法论、全面租房补贴与健身房', 1, '字节跳动_抖音/TikTok核心产品经理_https://job.bytedance.com/campus/position/detail/216');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_017', '中国电信集团有限公司', '电信运营商/算力', '2027秋招', '["技术研发"]', '["北京","上海","广州","成都"]', '天翼云研发工程师（分布式存储/容器网络/智算中心）', 'CT2027CLOUD', 'https://job.chinatelecom.cn/job/1701', '2026-09-16T14:20:00Z', '2026-11-15T23:59:59Z', 'active', '国云主力军核心项目、央企骨干编制、技术津贴、全流程落户辅导', 1, '中国电信集团有限公司_天翼云研发工程师（分布式存储/容器网络/智算中心）_https://job.chinatelecom.cn/job/1701');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_018', '中国联合网络通信集团有限公司', '电信运营商', '2027秋招', '["技术研发","解决方案"]', '["北京","济南","南京","武汉"]', '联通数科大数据与AI工程师', '', 'https://zglt.zhaopin.com/job/detail/1801', '2026-09-16T16:00:00Z', '2026-11-20T23:59:59Z', 'active', '数字化新引擎、健全的青年骨干成长快车道、企业年金与丰厚节日慰问', 1, '中国联合网络通信集团有限公司_联通数科大数据与AI工程师_https://zglt.zhaopin.com/job/detail/1801');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_019', '中国中车股份有限公司', '轨道交通/高端制造', '2027秋招', '["技术研发"]', '["株洲","青岛","大连","北京"]', '高铁电力牵引与列控算法研发工程师', 'CRRC2027GO', 'https://crrcgc.zhaopin.com/position/1901', '2026-09-15T09:00:00Z', '2026-12-01T23:59:59Z', 'active', '大国重器研发平台、事业编制/国企核心待遇、提供人才定向购房补贴', 1, '中国中车股份有限公司_高铁电力牵引与列控算法研发工程师_https://crrcgc.zhaopin.com/position/1901');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_020', '中国航空工业集团有限公司', '航空航天/国防军工', '2027秋招', '["技术研发"]', '["成都","沈阳","西安","上海"]', '飞机飞控与航电软件系统工程师（主机研究所）', '', 'https://avic.zhiye.com/job/detail/2001', '2026-09-15T15:00:00Z', '2026-11-25T23:59:59Z', 'active', '航空报国崇高事业平台、解决重点城市户口、配套职工福利房及安家费', 1, '中国航空工业集团有限公司_飞机飞控与航电软件系统工程师（主机研究所）_https://avic.zhiye.com/job/detail/2001');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_021', '中国建设银行', '银行/金融', '2027秋招', '["职能管培","金融业务"]', '["北京","上海","深圳","全国"]', '总行/直属机构未来金融家管培生', '', 'http://job.ccb.com/job/2101', '2026-09-14T08:30:00Z', '2026-10-31T24:00:00Z', 'active', '总行多岗位轮岗机会、全球化视野赋能、七险二金与子女医疗互助', 1, '中国建设银行_总行/直属机构未来金融家管培生_http://job.ccb.com/job/2101');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_022', '中信证券股份有限公司', '证券/投资银行', '2027秋招', '["金融业务","技术研发"]', '["深圳","北京","上海"]', '金融科技与量化交易系统开发工程师', 'CITIC2027TECH', 'https://customer.citics.com/recruitment/job/2201', '2026-09-14T11:00:00Z', '2026-11-15T23:59:59Z', 'active', '券商航母核心核心平台、顶尖量化回测系统实操、市场化高额激励奖金', 1, '中信证券股份有限公司_金融科技与量化交易系统开发工程师_https://customer.citics.com/recruitment/job/2201');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_023', '招商银行股份有限公司', '银行/金融科技', '2027秋招', '["技术研发"]', '["深圳","杭州"]', '招银网络科技-全栈软件开发工程师', 'CMBTECH2027', 'https://career.cloud.cmbchina.com/job/2301', '2026-09-13T10:00:00Z', '2026-11-10T23:59:59Z', 'active', '银行界公认Fintech领跑者、全额缴纳公积金、补充商业医疗保险及餐补', 1, '招商银行股份有限公司_招银网络科技-全栈软件开发工程师_https://career.cloud.cmbchina.com/job/2301');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_024', '小米集团', '智能硬件/消费电子', '2027秋招', '["技术研发"]', '["北京","武汉","深圳"]', '澎湃OS系统架构研发工程师', 'MI2027VIP', 'https://hr.xiaomi.com/campus/position/2401', '2026-09-13T14:30:00Z', '2026-12-10T23:59:59Z', 'active', '人车家全生态核心基座研发、员工买房超低利息贷款、全套小米智能家电内购', 1, '小米集团_澎湃OS系统架构研发工程师_https://hr.xiaomi.com/campus/position/2401');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_025', '宁德时代新能源科技股份有限公司', '新能源/动力电池', '2027秋招', '["技术研发"]', '["宁德","上海","厦门","深圳"]', '电芯材料研发工程师 / 电池管理系统(BMS)工程师', 'CATLHR2027', 'https://talent.catl.com/job/2501', '2026-09-12T09:15:00Z', '2026-12-20T23:59:59Z', 'active', '全球动力电池霸主、顶尖实验室研发配套、丰厚安家安置费、海外出差补贴', 1, '宁德时代新能源科技股份有限公司_电芯材料研发工程师 / 电池管理系统(BMS)工程师_https://talent.catl.com/job/2501');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_026', '中芯国际', '半导体/芯片制造', '2027秋招', '["技术研发","工程技术"]', '["上海","北京","天津","深圳"]', '集成电路工艺整合工程师 (PIE)', 'SMICCHIP2027', 'https://smics.zhiye.com/job/2601', '2026-09-12T16:00:00Z', '2026-11-30T23:59:59Z', 'active', '集成电路国家支柱、快速解决一线城市户口、员工配套公租房及班车', 1, '中芯国际_集成电路工艺整合工程师 (PIE)_https://smics.zhiye.com/job/2601');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_027', '百度', '互联网/人工智能', '2027秋招', '["技术研发"]', '["北京","上海","深圳"]', '文心大模型预训练/微调工程师', 'BAIDUVIP2027', 'https://talent.baidu.com/jobs/campus-item?id=2701', '2026-09-11T13:00:00Z', '2026-11-15T23:59:59Z', 'active', 'AI黄埔军校底层框架浸润、百度飞桨生态直通、顶配弹性工时与健身房', 1, '百度_文心大模型预训练/微调工程师_https://talent.baidu.com/jobs/campus-item?id=2701');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_028', '拼多多', '互联网/跨境电商', '2027提前批', '["技术研发"]', '["上海"]', '服务端研发工程师（TEMU全球化电商中台）', 'PDD2027TOP', 'https://careers.pinduoduo.com/campus/detail?id=2801', '2026-09-11T17:00:00Z', '2026-10-25T23:59:59Z', 'active', '业界顶尖薪酬竞争力、出海业务高速增长风口、包三餐与水果点心零食', 1, '拼多多_服务端研发工程师（TEMU全球化电商中台）_https://careers.pinduoduo.com/campus/detail?id=2801');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_029', '网易公司', '游戏/文娱', '2027提前批', '["技术研发","美术设计"]', '["广州","杭州","上海"]', '游戏引擎/客户端研发工程师（互娱卓越项目）', 'NETEASE2027G', 'https://campus.163.com/job/2901', '2026-09-10T10:00:00Z', '2026-11-05T23:59:59Z', 'active', '猪厂食堂名扬天下免费四餐、自研顶尖Messiah引擎实践、浓厚游戏文化', 1, '网易公司_游戏引擎/客户端研发工程师（互娱卓越项目）_https://campus.163.com/job/2901');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_030', '中国铁建股份有限公司', '建筑工程', '2027秋招', '["工程技术","职能管培"]', '["北京","成都","西安","广州","全国"]', '铁建栋梁管培生（桥隧/城轨/智能勘察设计院）', '', 'https://crcc.zhiye.com/job/3001', '2026-09-10T15:00:00Z', '2026-12-10T23:59:59Z', 'active', '万亿基建领头羊央企、完备的青年干部培养导师制、全额住房公积金与六险', 1, '中国铁建股份有限公司_铁建栋梁管培生（桥隧/城轨/智能勘察设计院）_https://crcc.zhiye.com/job/3001');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_031', '中国石油天然气集团有限公司', '石油化工/能源', '2027秋招', '["技术研发","职能管培"]', '["北京","大庆","成都","西安","全国"]', '油气勘探开发及新能源技术管培生', '', 'https://zhaopin.cnpc.com.cn/job/3101', '2026-09-09T09:00:00Z', '2026-10-25T18:00:00Z', 'active', '老牌骨干央企保障、国家重点实验室科研平台、企业年金、职工带薪疗休养', 1, '中国石油天然气集团有限公司_油气勘探开发及新能源技术管培生_https://zhaopin.cnpc.com.cn/job/3101');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_032', '中国中化控股有限责任公司', '化工/材料', '2027秋招', '["技术研发","市场运营"]', '["北京","上海","扬州","连云港"]', '新材料与绿色化工科技研发工程师', 'SINOCHEM2027', 'https://sinochem.zhiye.com/job/3201', '2026-09-09T14:00:00Z', '2026-11-20T23:59:59Z', 'active', '万亿级综合化工航母、全球科研轮岗契机、完善的人才安居和健康守护体系', 1, '中国中化控股有限责任公司_新材料与绿色化工科技研发工程师_https://sinochem.zhiye.com/job/3201');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_033', '联想集团', 'IT/计算机软硬件', '2027秋招', '["技术研发","产品经理"]', '["北京","上海","武汉","深圳"]', 'AI PC端侧智能化软件架构师（管培生）', 'LENOVO2027FUTURE', 'https://talent.lenovo.com.cn/job/3301', '2026-09-08T11:00:00Z', '2026-11-15T23:59:59Z', 'active', '全球500强跨国办公文化、不加班WLB标杆企业、15天超长带薪年假', 1, '联想集团_AI PC端侧智能化软件架构师（管培生）_https://talent.lenovo.com.cn/job/3301');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_034', '海尔智家股份有限公司', '智能家电/物联网', '2027秋招', '["技术研发","市场运营"]', '["青岛","上海","北京"]', '三翼鸟智慧家庭IOT全栈研发工程师', 'HAIER2027MAKER', 'https://maker.haier.net/job/3401', '2026-09-08T15:30:00Z', '2026-11-30T23:59:59Z', 'active', '人单合一创客文化、青岛海景园区、员工低息免息购房无忧计划', 1, '海尔智家股份有限公司_三翼鸟智慧家庭IOT全栈研发工程师_https://maker.haier.net/job/3401');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_035', '蚂蚁科技集团股份有限公司', '金融科技/互联网', '2027提前批', '["技术研发"]', '["杭州","上海","北京"]', '隐私计算与Web3密码学研发专家（科技星）', 'ANTSTAR2027', 'https://talent.antgroup.com/campus/detail?id=3501', '2026-09-07T10:00:00Z', '2026-10-30T23:59:59Z', 'active', '世界领先安全科技团队、高额科技津贴与期权分配、iHome置业贷款借款', 1, '蚂蚁科技集团股份有限公司_隐私计算与Web3密码学研发专家（科技星）_https://talent.antgroup.com/campus/detail?id=3501');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_036', '腾讯控股有限公司', '互联网/软件', '日常实习', '["技术研发"]', '["深圳","广州","北京"]', '前端开发日常实习生（长期招募-转正率极高）', 'TXINTERN2026', 'https://join.qq.com/intern/detail?id=3601', '2026-09-18T16:00:00Z', '2026-12-31T23:59:59Z', 'active', '日薪400-600元、异地租房补贴每月1500元、早晚全城豪华大巴接送', 1, '腾讯控股有限公司_前端开发日常实习生（长期招募-转正率极高）_https://join.qq.com/intern/detail?id=3601');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_037', '字节跳动', '互联网/广告', '2026秋招补录', '["市场运营"]', '["北京","上海"]', '巨量引擎商业化投放运营经理（急招补录）', 'BYTEDANCEBULU', 'https://job.bytedance.com/campus/detail/3701', '2026-09-18T18:00:00Z', '2026-10-15T23:59:59Z', 'active', 'HC直出两周快速发Offer、商业闭环快速成长、免费下午茶及全套健身房', 1, '字节跳动_巨量引擎商业化投放运营经理（急招补录）_https://job.bytedance.com/campus/detail/3701');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_038', '美团', '互联网/自动配送', '日常实习', '["技术研发"]', '["北京","深圳"]', '自动车/无人机控制与规划算法实习生', 'MTINTERN2026', 'https://zhaopin.meituan.com/intern/detail?id=3801', '2026-09-17T17:00:00Z', '2026-11-30T23:59:59Z', 'active', '低空经济核心战略赛道、真机路测实战经验、导师倾囊相授、优秀者直发秋招绿卡', 1, '美团_自动车/无人机控制与规划算法实习生_https://zhaopin.meituan.com/intern/detail?id=3801');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_039', '大疆创新科技有限公司', '智能硬件', '日常实习', '["设计/创意","市场运营"]', '["深圳"]', '全球品牌影像创意制作与社媒运营实习生', 'DJICREAT2026', 'https://we.dji.com/zh-CN/intern/detail?id=3901', '2026-09-16T18:30:00Z', '2026-12-31T23:59:59Z', 'active', '全套大疆顶级无人机/云台免费把玩借用、高规格影像棚制作体验、实习薪酬优厚', 1, '大疆创新科技有限公司_全球品牌影像创意制作与社媒运营实习生_https://we.dji.com/zh-CN/intern/detail?id=3901');
INSERT OR REPLACE INTO job_referrals (id, company_name, industry, recruitment_type, job_categories, cities, job_title, referral_code, apply_url, publish_time, deadline, status, highlights, is_official_sync, dedup_hash) VALUES ('job_040', '华为技术有限公司', 'ICT/数通', '2026秋招补录', '["技术研发"]', '["西安","成都","南京"]', '网络技术工程师/技术支持专家（紧急补招）', 'HWFASTPASS', 'https://career.huawei.com/job/4001', '2026-09-18T19:00:00Z', '2026-10-20T23:59:59Z', 'active', '快速面试直通车、高起薪+常驻基地津贴、全球化工程实战阅历', 1, '华为技术有限公司_网络技术工程师/技术支持专家（紧急补招）_https://career.huawei.com/job/4001');
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_001', '2026-2027北森在线测评 (Beisen) 全模块通关真题库与高分破局指南', '在线测评真题', '汇总北森系统言语理解、数字推理、逻辑推理、情境判断及职业性格测评题库，附详细解析公式与秒杀答题技巧。', 'PDF + 题库模拟Excel', 'https://pan.quark.cn/s/beisen_2026_exam_pack', 'bs88', 15);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_002', '互联网大厂历年笔试编程真题详解与高频LeetCode冲刺合集（腾讯/阿里/字节/美团/快手）', '大厂笔试编程', '历届秋招春招编程题真题代码与复盘（涵盖动态规划、树图论搜索、贪心、大数处理），全解支持C++/Java/Python/Go多语言。', 'Markdown + PDF + 源码Zip', 'https://pan.baidu.com/s/1dache_code_exam_master', 'code', 20);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_003', '国家电网历年统考（电工类/通信类/计算机类）真题卷及高频核心考点秘籍', '央国企笔试', '含国家电网一批、二批历年真题及模拟卷，覆盖电路、电磁场、电力系统分析及行测公共基础知识解析。', '高清PDF扫描件', 'https://pan.quark.cn/s/sgcc_exam_real_questions', 'sg26', 18);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_004', '中国移动/电信/联通运营商秋招统考专业技术与综合素质题库汇总', '央国企笔试', '针对三大运营商机考行测、通信原理、计算机网络常识及企业文化专属模块的历年高频真题归纳总结。', 'PDF电子书', 'https://pan.baidu.com/s/1telecom_operator_prep', '1008', 15);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_005', '国有六大行及股份制银行校招通用机考 (EPI+综合知识+英语) 冲刺宝典', '银行笔试', '工行、建行、中行、农行通用笔试题库：EPI职业能力测试技巧、微观宏观经济金融常识、托业英语解题技巧套卷。', 'PDF + Word模考卷', 'https://pan.quark.cn/s/bank_campus_epi_bundle', 'bank', 15);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_006', '顶尖投行与头部券商（中金/中信/华泰）核心估值建模与财务分析面试圣经', '券商投行', '经典三张表联动实操、DCF模型、LBO收购模型Excel实战模版，以及投行常考400问（Vault Guide & BIWS精华中译版）。', 'Excel财务模型 + PDF', 'https://pan.baidu.com/s/1ibd_cicc_modeling_pack', 'ibd8', 20);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_007', '常春藤与名企HR一致好评的中英文精选投行/大厂校招简历模板库（Word/LaTeX）', '简历模板', '包含30套通过ATS机器初筛的高通过率单页简历模板，针对技术开发、产品经理、行研分析、综合管培分类优化排版。', 'Word + Overleaf LaTeX源文件', 'https://pan.quark.cn/s/ivy_ats_resume_templates', 'cv99', 10);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_008', '产品经理校招冲刺课件：大厂竞品分析框架、PRD原型设计与商业化实战手册', '求职技能', '美团/腾讯/小红书资深产品总监审定：产品思维破局、指标体系统计、AB实验设计规范与高分竞品分析报告范本。', 'PDF + Axure源文件', 'https://pan.baidu.com/s/1pm_master_campus_pack', 'pm66', 15);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_009', '华为通用软件/算法历年上机机考题库（牛客网高频代码全AC解析）', '硬件大厂笔试', '华为机考三道题分值（100+100+200分）深度解析，覆盖递归回溯、DFS/BFS、图论并查集与字符串高效处理模板。', 'PDF + Python/C++源码工程', 'https://pan.quark.cn/s/huawei_oj_exam_ac', 'hw88', 18);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_010', '中石油/中石化通用能力考试综合知识与思想政治素养考点精华', '央国企笔试', '中石油中石化全国初选机考真题大纲全覆盖：行测常识、企业核心精神、时政热点题库与考前密押300题。', 'PDF电子书', 'https://pan.baidu.com/s/1petro_exam_guide', 'sino', 12);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_011', '无领导小组讨论 (群面) 破局秘籍：角色分工、框架搭建与20个高频真题演练', '面试技巧', '攻克国企与大厂管培群面杀手锏：破冰者Leader、时间把控Timer、结构框架搭建Recorder、陈述汇报Reporter万能话术模板。', '高清思维导图 + PDF演讲录音稿', 'https://pan.quark.cn/s/group_interview_star_handbook', 'star', 12);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_012', '结构化面试与宝洁八大问 (STAR原则) 满分答辩范文库（通用国企/外企/大厂）', '面试技巧', '如何将大学项目、社团经历、竞赛成果精炼为标准STAR模型（情境-目标-行动-结果），附50篇可以直接套用的高分回答范本。', 'Word可编辑文档 + PDF', 'https://pan.baidu.com/s/1pg8_star_interview_guide', 'pg88', 10);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_013', '大厂系统设计 (System Design) 面试速成：从零设计短链系统到千万人流即时通讯', '技术面试', '高并发、高可用架构设计考题全攻略：限流降级、分布式缓存Redis、消息队列Kafka、分库分表及一致性协议深度推演。', 'PDF电子书 + 架构白板脑图', 'https://pan.quark.cn/s/system_design_interview_roadmap', 'sys8', 18);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_014', '大模型 (LLM) 与AIGC前沿岗位秋招复习指南：从Transformer架构到RAG/微调实战', '技术面试', '针对大模型算法/研发校招热点：Attention机制推导、LoRA微调实战、Prompt工程、向量检索与LangChain核心概念速通速记卡。', 'PDF手写推导笔记 + 源码Notebook', 'https://pan.baidu.com/s/1llm_interview_handbook', 'llm7', 20);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_015', '中车/中航/建筑央企综合素质测评与工程力学/机械设计基础速成小抄', '央国企笔试', '中国中车及中航工业下属主机厂/研究院笔试综合基础汇总，含材料力学、理论力学常考概念公式速查。', 'PDF精编打印版', 'https://pan.quark.cn/s/crrc_avic_engineering_prep', 'mech', 12);
INSERT OR REPLACE INTO resource_materials (id, title, category, description, file_format, drive_url, access_code, points_required) VALUES ('res_016', '字节跳动/腾讯互联网英文岗位国际化业务全英文面试常考QA与口语音频包', '外企与全球化', '针对TikTok/海外游戏/跨境电商岗位的全英文简历深挖、Behavioral Question与产品拆解标准回答及发音示例。', 'MP3音频 + PDF对照手册', 'https://pan.baidu.com/s/1global_interview_english_pack', 'eng8', 15);
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_001', '双非本985硕上岸腾讯微信后台开发SP级Offer！四轮技术面+HR面全真复盘', '腾讯控股有限公司', '技术研发-后台开发', '技术终面/HR面', '高并发网络IO与分布式存储', '从简历被捞、一面被问穿Epoll多路复用底层，到三面深挖Raft共识算法及手写LRU Cache，最终拿下微信核心团队SP级的完整上岸经历。', '【背景 Situation】普通211本科保研985，实验室研究分布式计算。目标是微信广州技术团队。
【任务 Task】在简历无大厂实习背景下，需要靠过硬的计算机底层基础和开源中间件项目赢得面试官认可。
【行动 Action (STAR法则)】
1. 一面（基础深度）：面试官直击Linux网络协议栈，要求详尽拆解TCP三次握手报文状态迁移，以及EPOLLLT和EPOLLET在高并发下的性能与惊群效应处理。我结合源码解析了epoll红黑树+就绪链表的机制。
2. 二面（项目深挖）：就我实现的轻量级Raft集群展开，问到选举脑裂场景、日志压缩快照机制及日志乱序复制故障恢复，我通过画架构状态转移图清晰剖析。
3. 三面（系统设计与手撕）：要求手写带并发保护的LRU Cache（基于双向链表+哈希表+读写锁），并设计一个高并发微信抢红包架构（重点解答了预扣库存、Redis Lua脚本原子操作与异步账务入库）。
【结果 Result】面完三天收到HR面通知，一周内收到正式录用意向书，薪资定级SP档。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_002', '字节跳动商业化后端三轮技术面连打+手撕Hard算法题硬核上岸通关记', '字节跳动', '技术研发-服务端开发', '技术三面', '操作系统、Golang高并发调度与算法手撕', '字节面试特点是高密度手撕算法+底层八股极限追问。本文深度复盘GMP调度模型细节、内存逃逸分析及接雨水变种题解题套路。', '【背景 Situation】计算机本硕，投递字节跳动北京巨量引擎商业化架构组。
【任务 Task】扛住字节著名的连续三轮技术轰炸，完成2道Hard/Medium手撕代码并回答深入底层的八股。
【行动 Action】
1. 算法题：分别手写了K个一组翻转链表、二叉树最大路径和，以及LRU缓存。面试官特意要求在白板编辑器无代码提示、零编译环境下一次性通过，并计算时间复杂度。
2. Golang深度：追问Goroutine调度器的sysmon线程作用、网络轮询器netpoller机制、Channel的环形缓冲区与hchan锁竞争优化。
3. MySQL与Redis实战：解释为什么B+树比B树更适合磁盘索引，以及在数十万QPS高并发下的缓存击穿、穿透与雪崩应对全套降级方案。
【结果 Result】当晚系统显示面试全部通过，次日HR沟通意向。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_003', '跨考非科班拿国家电网上海市电力公司一批统考第一名经验分享', '国家电网有限公司', '电气工程与调度运维', '统一笔试+综合面试', '专业笔试核心题型、半结构化面试自我介绍与压力问答', '详细梳理国网笔试电路/电力系统70分大头得分策略，以及上海国网面试双盲抽签、半结构化抽题答辩与家庭情况问询的最佳应答范式。', '【背景 Situation】控制工程转考电气，面临国网笔试高淘汰率和综合面试两道关卡。
【任务 Task】在短时间内攻坚电路理论、电力系统暂态稳态分析以及继电保护三大硬门槛，同时在结构化面试中脱颖而出。
【行动 Action】
1. 笔试攻坚：按照国家电网考纲刷完近5年历年真题及中国电力出版社配套习题，针对高频潮流计算、短路电流计算进行专题归纳，最终笔试考出81.5的高分。
2. 综合面试：国网面试为结构化抽题：抽到了‘谈谈新型电力系统下大规模新能源并网对电网调频调峰带来的挑战及应对手段’。运用STAR法则从源网荷储四端切入，结合储能系统技术逻辑层次清晰作答；面对考官关于‘是否服从郊区变电站一线倒班’的压力问题，真诚表达基层扎实历练的决心。
【结果 Result】综合成绩排名专业组第一，顺利签约上海市电力公司直属单位。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_004', '华为中央软件院秋招14级直通：从上机满分到业务主管面综合素养复盘', '华为技术有限公司', '技术研发-软件工程', '业务主管面/综合面', '项目架构设计、开源经历深挖与文化价值观匹配', '解密华为上机机考技巧、专业一二面深度技术方案质询，以及如何通过业务主管综合面的压力性挑战。', '【背景 Situation】通信工程硕士，参与过开源Linux底层驱动开发及学术论文发表。
【任务 Task】通过华为机考门槛，并在专业两轮技术面试中展现强大的工程落地解决能力。
【行动 Action】
1. 机考：第一题简单模拟（100分），第二题贪心+双指针（100分），第三题树形动态规划（200分），30分钟完成前两题，第三题采用带备忘录的深度优先搜索拿到满分。
2. 专业面：面试官非常关注代码的可维护性与异常安全，重点考察了Linux内核态与用户态数据拷贝优化（Zero-Copy零拷贝技术，如mmap与sendfile对比），以及多线程互斥锁与自旋锁在NUMA架构下的性能差异。
3. 主管面：主管针对面对重大攻坚项目延期风险如何决策提问，我引用过往开源社区PR冲突攻关的经历，展现了严密的逻辑闭环和韧性。
【结果 Result】获得华为最高等级蓝牌签约，录用为14级高级研发工程师。', 10, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_005', '阿里巴巴淘天集团Java后端研发三轮面经：微服务高可用架构与MySQL内核调优', '阿里巴巴集团', '技术研发-Java服务端', '交叉面/技术二面', 'Java虚拟机内存模型、分布式事务Seata与分库分表实战', '淘天核心业务高并发面试实录：JVM GC垃圾回收排查全流程（从OOM Dump日志分析到Arthas在线诊断工具），以及分库分表下全局唯一ID生成的推演。', '【背景 Situation】计算机专业硕士，投递阿里巴巴淘天核心业务架构组。
【行动 Action】
1. JVM深入：面试官深入追问G1和ZGC垃圾收集器的并发标记周期与读写屏障机制，并现场给出一段伪代码，要求推演栈帧中的局部变量表逃逸与标量替换。
2. 分布式事务：详述2PC、TCC和基于消息最终一致性方案的优劣，针对订单-库存系统秒杀扣减的一致性问题，推导Redis+本地消息表+事务消息结合落地方案。
3. 线上故障定位：模拟一次生产环境CPU 100%和全堆内存泄漏的排查过程（top -H，jstack，jmap分析dump日志，结合Arthas watch实时追踪慢方法）。
【结果 Result】顺利通过技术交叉面与HR面，收获淘天核心Offer。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_006', '美团核心本地商业产品经理校招上岸：业务拆解、群面破局与业务负责人终面', '美团', '产品经理', '群面/总监终面', '互联网商业化模式、用户体验漏斗模型与需求优先级排序', '详细还原美团产品校招全流程：8人无领导小组讨论如何巧妙争取Timer和框架制定者角色，以及终面如何拆解美团即时零售在下沉市场的供给侧破局方案。', '【背景 Situation】经管交叉背景硕士，有一段中厂商业化实习经历。
【行动 Action】
1. 群面阶段：题目为‘针对美团外卖高价值白领用户设计一款提升午餐时段复购率的功能机制’。在大家争相抢当Leader时，我主动承担Timer并率先在白板上列出‘用户画像拆解-痛点场景归纳-解决方案筛选-收益评估漏斗’四步分析法，引导团队顺利在时限前输出闭环方案。
2. 业务面：面试官要求评估‘美团闪购与叮咚买菜在供应链前置仓上的效率差异’。我从SKU丰富度、履约履约半径、损耗率与单均履约成本四个维度做了严谨对比分析。
【结果 Result】产品群面全组唯一通过，终面获评优秀产品新人评级。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_007', '中国工商银行软件开发中心（珠海/广州）秋招技术面+无领导群面上岸全记录', '中国工商银行', '金融科技-软件研发', '半结构化+群面', '分布式银行核心账务系统设计理念与团队协同能力', '央企大行软开面试全透视：技术半结构化问答紧扣Spring Cloud金融级微服务拆分，群面讨论围绕银行业务智能化转型方案的推敲与立论。', '【背景 Situation】重点高校软件工程专业，追求一线大行稳定发展与落户待遇。
【行动 Action】
1. 技术单面：工行面试官非常注重安全与稳健，重点问了分布式锁在高并发转账场景下的幂等性保证，以及金融交易系统的灰度发布与容灾双活部署模式。
2. 综合群面：10人一组，讨论‘传统商业银行柜面业务AI智能化改造如何平衡银发老人体验与数字化效率’。我提出了‘分流引导+无障碍大字语音AI助手+兜底人工绿色通道’的渐进式混合服务方案，获得考官一致赞赏。
【结果 Result】收到工行总行软开中心Offer。', 7, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_008', '大疆创新嵌入式研发校招：从硬件原理图、Linux驱动到FreeRTOS实时操作系统', '大疆创新科技有限公司', '技术研发-嵌入式软硬件', '技术二面', '底层总线协议、中断嵌套与实时任务调度', '大疆对硬件底层功底要求极高。本文详细复盘I2C/SPI通信时序故障诊断、DMA传输缓冲区管理以及FreeRTOS优先级反转解决案例。', '【背景 Situation】自动化/电子信息工程硕士，参加过全国大学生智能汽车竞赛与RoboMaster机甲大师赛。
【行动 Action】
1. 硬件电路原理：面试官拿出一张电机驱动电路原理图，现场问答MOSFET选型、续流二极管作用及RC吸收电路参数计算。
2. RTOS底层原理：深入手撕FreeRTOS任务控制块（TCB），详述任务就绪列表与时间片轮转调度，重点解释互斥量（Mutex）利用优先级继承机制解决高低优先级任务反转死锁的具体过程。
3. 实机调试：结合RoboMaster调试底盘CAN总线丢包的经历，讲透利用示波器捕捉波形反射并添加120欧姆终端电阻抗匹配的解决过程。
【结果 Result】两轮技术考核均给出最高评级，顺利拿下大疆嵌入式研发Offer。', 9, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_009', '中金公司投资银行部 (IBD) 暑期实习转正秋招面经：估值模型、财务尽调与Pitchbook', '中国国际金融股份有限公司', '金融业务-投资银行分析师', '合伙人MD面', '企业三张财务报表拆解、IPO上市红线与商业逻辑判断', '顶级投行校招实录：面对董事总经理（MD）长达45分钟的高压商业盘问，如何以严谨的财务逻辑与出色的抗压能力赢下全职Offer。', '【背景 Situation】顶尖高校金融硕士，有一段券商行研和内资投行实习。
【行动 Action】
1. 财务技术面（Technical）：直接现场考核‘如果一家公司发生100万元的资本性支出（CapEx），折旧年限为10年，假设企业所得税率为25%，三张报表在第一年该如何变动？’清晰准确回答出现金流量表、利润表及资产负债表平衡变动过程。
2. 行业与商业逻辑：面试官针对新能源光伏出海企业提出假设场景，要求快速搭建SWOT分析及盈利预测敏感性分析，指出关键风险点（反补贴关税政策及汇率波动）。
3. 行为测试（Fit）：针对‘如何应对持续数周凌晨两点的紧急改稿？’展现了高抗压、精细度至上的投行专业精神。
【结果 Result】成功从数百名实习生中斩获全职Analyst录用通知。', 10, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_010', '快手大模型推荐算法工程师秋招复盘：从多任务学习框架到强化学习实时排序', '快手科技', '技术研发-算法工程师', '技术二面/终面', 'CTR预估、MMoE多门控混合专家网络与冷启动机制', '短视频顶流快手算法校招实操：拆解亿级播放量下的短视频推荐系统链路（召回、粗排、精排、重排），并深入手推Transformer多头自注意力与梯度反向传播。', '【背景 Situation】计算机应用技术硕士，实验室方向为图神经网络与信息推荐。
【行动 Action】
1. 经典模型深度：详细推导MMoE和PLE如何解决短视频多目标（点击率CTR与完播率、点赞率、转发率）之间的负迁移与跷跷板效应。
2. 特征工程与在线计算：讨论百亿级特征下Embedding查表延迟优化，以及在线流式训练Parameter Server架构设计。
3. 手撕算法：要求在无内置库辅助下手写K-Means聚类算法收敛过程，并手动推导Softmax损失函数的反向求导公式。
【结果 Result】入选快手‘快星’顶尖人才计划并获得Offer。', 9, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_011', '比亚迪汽车工程研究院智能网联研发校招：从AUTOSAR架构到CAN网络通信', '比亚迪股份有限公司', '智能制造-整车软件工程师', '技术专业面', '车载总线协议、汽车安全功能ISO26262与C语言底层优化', '新能源汽车霸主校招面试实况：车载ECU固件升级（UDS诊断协议0x27安全访问机制）、CAN-FD与车载以太网的未来演进。', '【背景 Situation】车辆工程与计算机交叉学科背景。
【行动 Action】
1. 车载通信协议：详述传统CAN总线与CAN-FD在数据段长度与波特率切换上的底层区别，解释位填充机制与CRC校验位在物理层的纠错过程。
2. 汽车软件标准：围绕AUTOSAR经典平台分层架构（BSW、RTE与应用层SWC）进行模块化接口拆解。
3. 综合问答：讨论了比亚迪刀片电池与CTB（电池车身一体化）技术对于整车刚度及动力学控制的影响。
【结果 Result】面试当天通过并直接完成线上意向签约。', 7, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_012', '中国建筑八局/三局总部管培生结构化面试与二测通关经验分享', '中国建筑集团有限公司', '职能管培/工程技术', '测评二测+局院线下面试', '施工组织设计编制、安全质量风险控制与团队服从执行力', '中建系统校园招聘两轮统一测评通过技巧，以及在工程局总部直面考官时如何展现吃苦耐劳、善于统筹协同的央企工程师气质。', '【背景 Situation】土木工程与工程管理专业本科，立志在央企基建系统发展。
【行动 Action】
1. 中建一测与二测：提前刷透中建测评专项题库，掌握空间折叠纸盒、图形规律与类比推理的高频秒杀技巧，顺利稳拿全国认证成绩单。
2. 线下面试：局人事副局长亲自主考。围绕大型超高层项目雨季深基坑支护坍塌风险应急预案展开情境模拟，我结合实习工地实际案例，从地下水降水监测、应急加固支撑、人员分级疏散三个层面系统陈述。
3. 个人价值观：针对常驻项目部的工作性质，展现出扎根一线、向一线工程要经验的脚踏实地态度。
【结果 Result】顺利录用为中建八局总部优才管培生计划成员。', 6, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_013', '小红书社区生态与商业化产品经理三面通关复盘：用户共情与增长飞轮', '小红书', '产品经理', '业务总监面', 'UGC内容社区冷启动、种草到拔草链路闭环与推荐生态平衡', '以小红书重度用户视角拆解社区内容治理与商业化广告加载率（Ad Load）之间的博弈，拿下上海新天地总部产品管培Offer。', '【背景 Situation】传播学硕士，拥有小红书万粉个人IP创作经验。
【行动 Action】
1. 一面（用户体验与共情）：深入拆解小红书双列瀑布流点击率与单列沉浸式体验的心理差异，从探索型动机和消费心智进行了严密论证。
2. 二面（指标与策略）：探讨如何利用双向负反馈调节机制降低商业广告对自然内容生态的侵蚀，提出了基于用户停留时长与长效互动率的加权计费优化点。
3. 三面（终审）：面试官要求构想一款面向下沉市场银发银发族群的小红书适老化极简模式，我从大字视听辅助、熟人关系圈分享、去除了复杂图文创作门槛的‘拍同款’方案完成完整PRD构思。
【结果 Result】获得小红书全职产品经理意向书。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_014', '中国移动通信集团浙江移动IT技术研发岗校招统考+综合双面通关', '中国移动通信集团有限公司', '技术研发-云计算与大数据', '全省统考+专业双盲面试', '分布式微服务治理、网络运维自动化与团队沟通协调', '浙江移动作为全国运营商IT数字化标杆，其面试技术水平完全看齐一线互联网大厂。复盘Spring Cloud微服务与行测冲刺经验。', '【背景 Situation】信息与通信工程硕士，投递浙江移动杭州研发中心。
【行动 Action】
1. 全国统考：行测与专业综合考试，重点提升资料分析速算和逻辑推理速度，最终笔试在浙江省名列前茅。
2. 综合专业面试：面试采用多对一双盲模式。考官重点考核微服务架构中熔断降级（Sentinel/Hystrix底层原理）、分布式链路追踪（SkyWalking）以及Docker容器化编排K8s的基本工作原理；同时结合移动营业厅‘双十一’充值缴费高并发峰值设计了消息队列平滑削峰填谷策略。
【结果 Result】成功拿到浙江移动省公司本部技术研发Offer。', 7, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_015', '小米集团手机部系统软件研发二面复盘：Linux内核内存管理与Android Framework', '小米集团', '技术研发-系统开发', '技术二面', 'Binder进程间通信机制、SurfaceFlinger渲染管道与内存回收', '小米澎湃OS团队硬核系统底层技术面实录，全面梳理Android Framework核心服务初始化过程与Linux虚拟内存映射调优。', '【背景 Situation】计算机科学与技术本科，主攻系统软件方向。
【行动 Action】
1. Android Framework底层：从Zygote进程孵化讲起，详解SystemServer启动核心服务过程，重点剖析Binder驱动底层基于mmap单次内存拷贝的实现原理。
2. 内存管理：深挖Linux Slab分配器原理、页面抖动与LowMemoryKiller触发机制，现场写出如何通过自定义Native崩溃信号捕获崩溃堆栈。
3. 算法手撕：高频手撕LRU缓存算法与二叉树后序遍历迭代写法，全部一次性AC并说明边界保护逻辑。
【结果 Result】顺利拿到小米系统软件研发部Offer。', 8, '大厂上岸复盘');
INSERT OR REPLACE INTO interview_experiences (id, title, company_name, position_type, round_tag, question_type, summary, detail_content, points_required, source_platform) VALUES ('exp_016', '中国中车青岛四方机车高铁电气设计研发校招上岸经验全梳理', '中国中车股份有限公司', '技术研发-电气工程师', '技术专业面+综合考评', '交流传动控制系统、电磁兼容性(EMC)与大型国企合规意识', '国家高速列车研发摇篮（青岛四方）面试实战回顾：矢量控制与直接转矩控制算法在动车组牵引电机的具体运用。', '【背景 Situation】电力电子与电力传动硕士，立志献身中国高铁轨道交通制造事业。
【行动 Action】
1. 专业技能考查：面试官围绕高速动车组牵引变流器主电路拓扑（四象限整流器+PWM逆变器）展开质询，要求现场手绘整流电路并详细解释空间矢量脉宽调制（SVPWM）在母线电压波动时的稳压控制策略。
2. 质量意识问答：高铁属于高安全性要求行业，面试官问及如果图纸发生设计冲突如何处理，我从工程标准化作业规范（SOP）和闭环复核机制给出了严谨作答。
【结果 Result】当场确认录用并在青岛四方签约国家重点实验室平台岗位。', 7, '大厂上岸复盘');
